### PR TITLE
KP-5971 Get sertificate for sanat.csc.fi from ACME

### PR DESCRIPTION
**Pull request by aajarven**
Previously vhost.conf was not managed by Ansible. The current conf from the site was translated into a Jinja template and is now managed by Ansible.

The certificates for the other two sites residing on this machine were not altered, nor was their configuration.

Dry-running only the apache configuration role using a custom inventory without the vaulted secrets produces the following diff:
```
vagrant@kpdev:~/scratch/Kielipankki-palvelut/servers/sanat$ ansible-playbook apache-only.yml --check -i inventories/production --private-key ~/.ssh/id_rsa_kielipankki --diff

PLAY [web] ******************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************
Enter passphrase for key '/home/vagrant/.ssh/id_rsa_kielipankki': 
Enter passphrase for key '/home/vagrant/.ssh/id_rsa_kielipankki': 
ok: [sanat.csc.fi]

TASK [apache_ssl : Install required packages] *******************************************************************************
changed: [sanat.csc.fi]

TASK [apache_ssl : Register ACME] *******************************************************************************************
changed: [sanat.csc.fi]

TASK [apache_ssl : Fetch certificate via ACME] ******************************************************************************
skipping: [sanat.csc.fi]

TASK [apache_ssl : Setup weekly cronjob for updating the certificate] *******************************************************
--- before
+++ after: /home/vagrant/.ansible/tmp/ansible-local-258071f0xjdf2/tmpoipkmk98
@@ -0,0 +1,3 @@
+#!/bin/bash
+# See https://wiki.csc.fi/PATA/Ohjeet/ServerCertificatesACME
+certbot renew --deploy-hook "systemctl reload httpd"

changed: [sanat.csc.fi]

TASK [apache_ssl : Copy vhost.conf] *****************************************************************************************
--- before: /etc/httpd/conf.d/vhosts.conf
+++ after: /home/vagrant/.ansible/tmp/ansible-local-258071f0xjdf2/tmpebxx9riu/vhosts.conf.j2
@@ -60,9 +60,9 @@
   SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
   SSLHonorCipherOrder On
   SSLCompression off
-  SSLCertificateFile /etc/pki/tls/certs/sanat_csc_fi_cert.cer
-  SSLCertificateKeyFile /etc/pki/tls/private/sanat_csc_fi.key
-  SSLCertificateChainFile /etc/pki/tls/certs/GEANT_OV_RSA_CA_4.cer
+  SSLCertificateFile  "/etc/letsencrypt/live/sanat.csc.fi/cert.pem"
+  SSLCertificateKeyFile "/etc/letsencrypt/live/sanat.csc.fi/privkey.pem"
+  SSLCertificateChainFile  "/etc/letsencrypt/live/sanat.csc.fi/chain.pem"
 
   <Directory "/www/sanat.csc.fi/docroot">
     AllowOverride All

changed: [sanat.csc.fi]

RUNNING HANDLER [apache_ssl : restart httpd] ********************************************************************************
changed: [sanat.csc.fi]

PLAY RECAP ******************************************************************************************************************
sanat.csc.fi               : ok=6    changed=5    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
```

### CODE REVIEW

**Comment by mmatthiesencsc** [comment]
Thanks Anni! Next up is Tieteentermipankki, but that should be rather trivial now.

**Comment by Nikerabbit** [comment]
For what it is worth, this partially breaks updating my development and testing environment with:
* Hard-coded domains and paths in the vhost
* Introducing unconditional calls to password store

**Comment by mmatthiesencsc** [comment]
Hi Niklas, ok, this should not be the case, we did not do it on purpose. We noticed the same with Vault. How do we find a working solution? I suggest we should meet and discuss it, I have no clear idea on how to proceed, I would be willing to share the encrypted password database outside of CSC, you can see the secrets anyway on the server, but I would need to discuss this internally.

**Comment by Nikerabbit** [comment]
Yeah I think we should meet and discuss. In any case, it's not urgent.

**Pull request merged**
